# Autogenerated wrapper script for zarray_jll for any
export zarray

using nlohmann_json_jll
using xsimd_jll
using xtensor_jll
JLLWrappers.@generate_wrapper_header("zarray")
JLLWrappers.@declare_file_product(zarray)
function __init__()
    JLLWrappers.@generate_init_header(nlohmann_json_jll, xsimd_jll, xtensor_jll)
    JLLWrappers.@init_file_product(
        zarray,
        "include/zarray/zarray.hpp",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
